version: "3"

services:
  artillery:
    build: .
    entrypoint: ["npm", "run", "profile"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      tracker:
        condition: service_healthy
    networks:
      - app-tier

networks:
  app-tier:
